spring.application.name=recipe-query-service
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.model=gpt-4.1
spring.ai.openai.model.embeddings=text-embedding-3-small

# Upstash Redis Config
upstash.redis-url=

# Upstash Vector Config
upstash.vector.url=https://liked-midge-43382-us1-vector.upstash.io
upstash.vector.token=