spring.application.name=recipe-query-service
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.model=gpt-4.1-mini

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Gateway Configuration
# server.port=8081
# spring.cloud.gateway.discovery.locator.enabled=true
# logging.level.root=DEBUG